const vehicles = 
[
  {
    "id": "bmw-x1",
    "brand": "BMW",
    "bk": "outros",
    "model": "X1 SDRIVE 1.8I",
    "year": "2011/2011",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "gasolina",
    "extra": "Vendido",
    "classic": false,
    "img": "imagens/bmwx1.webp",
    "folder": "bmwx1",
    "price": "Vendido",
    "cambio": "",
    "desc": "",
    "photos": [
      "imagens/bmwx1/1.webp",
      "imagens/bmwx1/2.webp",
      "imagens/bmwx1/3.webp",
      "imagens/bmwx1/4.webp",
      "imagens/bmwx1/5.webp",
      "imagens/bmwx1/6.webp",
      "imagens/bmwx1/7.webp",
      "imagens/bmwx1/8.webp"
    ]
  },
  {
    "id": "willys-overland",
    "brand": "Willys",
    "bk": "outros",
    "model": "OVERLAND",
    "year": "1951/1951",
    "color": "Verde",
    "hex": "#4a7c59",
    "fuel": "gasolina",
    "extra": null,
    "classic": true,
    "img": "imagens/willys.webp",
    "folder": "willys",
    "price": "R$50.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/willys/1.webp",
      "imagens/willys/2.webp",
      "imagens/willys/3.webp",
      "imagens/willys/4.webp",
      "imagens/willys/5.webp",
      "imagens/willys/6.webp",
      "imagens/willys/7.webp",
      "imagens/willys/8.webp"
    ]
  },
  {
    "id": "chevrolet-agile",
    "brand": "Chevrolet",
    "bk": "chevrolet",
    "model": "AGILE LTZ",
    "year": "2012/2013",
    "color": "Cinza",
    "hex": "#9ba3b0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/agile.webp",
    "folder": "agile",
    "price": "R$38.500,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/agile/1.webp",
      "imagens/agile/2.webp",
      "imagens/agile/3.webp",
      "imagens/agile/4.webp",
      "imagens/agile/5.webp",
      "imagens/agile/6.webp",
      "imagens/agile/7.webp",
      "imagens/agile/8.webp"
    ]
  },
  {
    "id": "chevrolet-astra",
    "brand": "Chevrolet",
    "bk": "chevrolet",
    "model": "ASTRA ADVANTAGE 2.0",
    "year": "2011/2011",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/astra.webp",
    "folder": "astra",
    "price": "R$40.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/astra/1.webp",
      "imagens/astra/2.webp",
      "imagens/astra/3.webp",
      "imagens/astra/4.webp",
      "imagens/astra/5.webp",
      "imagens/astra/6.webp",
      "imagens/astra/7.webp",
      "imagens/astra/8.webp"
    ]
  },
  {
    "id": "chevrolet-cruze",
    "brand": "Chevrolet",
    "bk": "chevrolet",
    "model": "CRUZE LT NB",
    "year": "2012/2012",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/cruze.webp",
    "folder": "cruze",
    "price": "R$55.000,00",
    "cambio": "Automatico",
    "desc": "",
    "photos": [
      "imagens/cruze/1.webp",
      "imagens/cruze/2.webp",
      "imagens/cruze/3.webp",
      "imagens/cruze/4.webp",
      "imagens/cruze/5.webp",
      "imagens/cruze/6.webp",
      "imagens/cruze/7.webp",
      "imagens/cruze/8.webp"
    ]
  },
  {
    "id": "chevrolet-onix",
    "brand": "Chevrolet",
    "bk": "chevrolet",
    "model": "ONIX 1.4 LT",
    "year": "2016/2017",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": "Vendido",
    "classic": false,
    "img": "imagens/onix.webp",
    "folder": "onix",
    "price": "Vendido",
    "cambio": "",
    "desc": "",
    "photos": [
      "imagens/onix/1.webp",
      "imagens/onix/2.webp",
      "imagens/onix/3.webp",
      "imagens/onix/4.webp",
      "imagens/onix/5.webp",
      "imagens/onix/6.webp",
      "imagens/onix/7.webp",
      "imagens/onix/8.webp"
    ]
  },
  {
    "id": "gm-celta",
    "brand": "GM",
    "bk": "chevrolet",
    "model": "CELTA 2P SPIRIT",
    "year": "2007/2008",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/celta.webp",
    "folder": "celta",
    "price": "R$25.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/celta/1.webp",
      "imagens/celta/2.webp",
      "imagens/celta/3.webp",
      "imagens/celta/4.webp",
      "imagens/celta/5.webp",
      "imagens/celta/6.webp",
      "imagens/celta/7.webp",
      "imagens/celta/8.webp"
    ]
  },
  {
    "id": "gm-meriva-preto",
    "brand": "GM",
    "bk": "chevrolet",
    "model": "MERIVA PREMIUM",
    "year": "2008/2008",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/merivapreto.webp",
    "folder": "merivapreto",
    "price": "R$26.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/merivapreto/1.webp",
      "imagens/merivapreto/2.webp",
      "imagens/merivapreto/3.webp",
      "imagens/merivapreto/4.webp",
      "imagens/merivapreto/5.webp",
      "imagens/merivapreto/6.webp",
      "imagens/merivapreto/7.webp",
      "imagens/merivapreto/8.webp"
    ]
  },
  {
    "id": "gm-meriva-verde",
    "brand": "GM",
    "bk": "chevrolet",
    "model": "MERIVA PREMIUM",
    "year": "2010/2011",
    "color": "Verde",
    "hex": "#27ae60",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/meriva.webp",
    "folder": "meriva",
    "price": "R$35.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/meriva/1.webp",
      "imagens/meriva/2.webp",
      "imagens/meriva/3.webp",
      "imagens/meriva/4.webp",
      "imagens/meriva/5.webp",
      "imagens/meriva/6.webp",
      "imagens/meriva/7.webp",
      "imagens/meriva/8.webp"
    ]
  },
  {
    "id": "gm-s10",
    "brand": "GM",
    "bk": "chevrolet",
    "model": "S10 ADVANTAGE S",
    "year": "2009/2009",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "flex",
    "extra": "Vendido",
    "classic": false,
    "img": "imagens/s10.webp",
    "folder": "s10",
    "price": "Vendido",
    "cambio": "",
    "desc": "",
    "photos": [
      "imagens/s10/1.webp",
      "imagens/s10/2.webp",
      "imagens/s10/3.webp",
      "imagens/s10/4.webp",
      "imagens/s10/5.webp",
      "imagens/s10/6.webp",
      "imagens/s10/7.webp",
      "imagens/s10/8.webp"
    ]
  },
  {
    "id": "fiat-punto-prata",
    "brand": "Fiat",
    "bk": "fiat",
    "model": "PUNTO ATTRACTIVE",
    "year": "2016/2016",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/puntoprata.webp",
    "folder": "puntoprata",
    "price": "R$46.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/puntoprata/1.webp",
      "imagens/puntoprata/2.webp",
      "imagens/puntoprata/3.webp",
      "imagens/puntoprata/4.webp",
      "imagens/puntoprata/5.webp",
      "imagens/puntoprata/6.webp",
      "imagens/puntoprata/7.webp",
      "imagens/puntoprata/8.webp"
    ]
  },
  {
    "id": "fiat-punto-essence",
    "brand": "Fiat",
    "bk": "fiat",
    "model": "PUNTO ATTRACTIVE",
    "year": "2011/2012",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/puntoessence.webp",
    "folder": "puntopreto",
    "price": "R$35.000,00",
    "cambio": "Automatico",
    "desc": "",
    "photos": [
      "imagens/puntopreto/1.webp",
      "imagens/puntopreto/2.webp",
      "imagens/puntopreto/3.webp",
      "imagens/puntopreto/4.webp",
      "imagens/puntopreto/5.webp",
      "imagens/puntopreto/6.webp",
      "imagens/puntopreto/7.webp",
      "imagens/puntopreto/8.webp"
    ]
  },
  {
    "id": "fiat-uno-mille",
    "brand": "Fiat",
    "bk": "fiat",
    "model": "UNO MILLE ECONOMY",
    "year": "2013/2013",
    "color": "Azul Escuro",
    "hex": "#1a3a5c",
    "fuel": "flex",
    "extra": "Vendido",
    "classic": false,
    "img": "imagens/unomille.webp",
    "folder": "unomille",
    "price": "Vendido",
    "cambio": "",
    "desc": "",
    "photos": [
      "imagens/unomille/1.webp",
      "imagens/unomille/2.webp",
      "imagens/unomille/3.webp",
      "imagens/unomille/4.webp",
      "imagens/unomille/5.webp",
      "imagens/unomille/6.webp",
      "imagens/unomille/7.webp",
      "imagens/unomille/8.webp"
    ]
  },
  {
    "id": "fiat-uno-vivace",
    "brand": "Fiat",
    "bk": "fiat",
    "model": "UNO VIVACE 1.0",
    "year": "2010/2011",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/unovivace.webp",
    "folder": "unovivace",
    "price": "R$33.500,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/unovivace/1.webp",
      "imagens/unovivace/2.webp",
      "imagens/unovivace/3.webp",
      "imagens/unovivace/4.webp",
      "imagens/unovivace/5.webp",
      "imagens/unovivace/6.webp",
      "imagens/unovivace/7.webp",
      "imagens/unovivace/8.webp"
    ]
  },
  {
    "id": "ford-fiesta",
    "brand": "Ford",
    "bk": "ford",
    "model": "FIESTA",
    "year": "2009/2010",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/fiesta.webp",
    "folder": "fiesta",
    "price": "R$32.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/fiesta/1.webp",
      "imagens/fiesta/2.webp",
      "imagens/fiesta/3.webp",
      "imagens/fiesta/4.webp",
      "imagens/fiesta/5.webp",
      "imagens/fiesta/6.webp",
      "imagens/fiesta/7.webp",
      "imagens/fiesta/8.webp"
    ]
  },
  {
    "id": "ford-focus",
    "brand": "Ford",
    "bk": "ford",
    "model": "FOCUS TITANIUM 2.0",
    "year": "2014/2015",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/focus.webp",
    "folder": "focus",
    "price": "R$ 45.000",
    "cambio": "",
    "desc": "",
    "photos": [
      "imagens/focus/1.webp",
      "imagens/focus/2.webp",
      "imagens/focus/3.webp",
      "imagens/focus/4.webp",
      "imagens/focus/5.webp",
      "imagens/focus/6.webp",
      "imagens/focus/7.webp",
      "imagens/focus/8.webp"
    ]
  },
  {
    "id": "ford-ka",
    "brand": "Ford",
    "bk": "ford",
    "model": "KA 1.0 SEL",
    "year": "2015/2015",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/ka.webp",
    "folder": "ka",
    "price": "R$42.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/ka/1.webp",
      "imagens/ka/2.webp",
      "imagens/ka/3.webp",
      "imagens/ka/4.webp",
      "imagens/ka/5.webp",
      "imagens/ka/6.webp",
      "imagens/ka/7.webp",
      "imagens/ka/8.webp"
    ]
  },
  {
    "id": "ford-maverick",
    "brand": "Ford",
    "bk": "ford",
    "model": "MAVERICK",
    "year": "1978/1979",
    "color": "Cinza",
    "hex": "#9ba3b0",
    "fuel": "gasolina",
    "extra": null,
    "classic": true,
    "img": "imagens/maverick.webp",
    "folder": "maverick",
    "price": "R$260.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/maverick/1.webp",
      "imagens/maverick/2.webp",
      "imagens/maverick/3.webp",
      "imagens/maverick/4.webp",
      "imagens/maverick/5.webp",
      "imagens/maverick/6.webp",
      "imagens/maverick/7.webp",
      "imagens/maverick/8.webp"
    ]
  },
  {
    "id": "hyundai-hb20",
    "brand": "Hyundai",
    "bk": "outros",
    "model": "HB20 1.6",
    "year": "2019/2019",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/hb20.webp",
    "folder": "hb20",
    "price": "",
    "cambio": "",
    "desc": "",
    "photos": [
      "imagens/hb20/1.webp",
      "imagens/hb20/2.webp",
      "imagens/hb20/3.webp",
      "imagens/hb20/4.webp",
      "imagens/hb20/5.webp",
      "imagens/hb20/6.webp",
      "imagens/hb20/7.webp",
      "imagens/hb20/8.webp"
    ]
  },
  {
    "id": "hyundai-hr",
    "brand": "Hyundai",
    "bk": "outros",
    "model": "HR HDB",
    "year": "2012/2013",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "diesel",
    "extra": null,
    "classic": false,
    "img": "imagens/hyundaihr.webp",
    "folder": "hyundaihr",
    "price": "R$89.900,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/hyundaihr/1.webp",
      "imagens/hyundaihr/2.webp",
      "imagens/hyundaihr/3.webp",
      "imagens/hyundaihr/4.webp",
      "imagens/hyundaihr/5.webp",
      "imagens/hyundaihr/6.webp",
      "imagens/hyundaihr/7.webp",
      "imagens/hyundaihr/8.webp"
    ]
  },
  {
    "id": "hyundai-tucson",
    "brand": "Hyundai",
    "bk": "hyundai",
    "model": "TUCSON GLSB",
    "year": "2012/2013",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "gasolina",
    "extra": null,
    "classic": false,
    "img": "https://d2xsxph8kpxj0f.cloudfront.net/310519663389657681/3zSJVq9qjkbxu9s8RVd9jK/1_fca99f0a.webp",
    "folder": "tucson",
    "price": "R$50.500,00",
    "cambio": "Automatico",
    "desc": "",
    "photos": [
      "https://d2xsxph8kpxj0f.cloudfront.net/310519663389657681/3zSJVq9qjkbxu9s8RVd9jK/1_fca99f0a.webp",
      "https://d2xsxph8kpxj0f.cloudfront.net/310519663389657681/3zSJVq9qjkbxu9s8RVd9jK/3_c71e76a2.webp",
      "https://d2xsxph8kpxj0f.cloudfront.net/310519663389657681/3zSJVq9qjkbxu9s8RVd9jK/6_6ab7dbdb.webp"
    ]
  },
  {
    "id": "kia-uk2500",
    "brand": "Kia Motors",
    "bk": "outros",
    "model": "UK2500 HD SC",
    "year": "2013/2014",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "diesel",
    "extra": null,
    "classic": false,
    "img": "imagens/kia.webp",
    "folder": "kia",
    "price": "R$150.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/kia/1.webp",
      "imagens/kia/2.webp",
      "imagens/kia/3.webp",
      "imagens/kia/4.webp",
      "imagens/kia/5.webp",
      "imagens/kia/6.webp",
      "imagens/kia/7.webp",
      "imagens/kia/8.webp"
    ]
  },
  {
    "id": "mitsubishi-asx",
    "brand": "Mitsubishi",
    "bk": "mitsubishi",
    "model": "ASX 2.0 4WD",
    "year": "2013/2013",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/asx.webp",
    "folder": "asx",
    "price": "R$74.000,00",
    "cambio": "Automatico",
    "desc": "",
    "photos": [
      "imagens/asx/1.webp",
      "imagens/asx/2.webp",
      "imagens/asx/3.webp",
      "imagens/asx/4.webp",
      "imagens/asx/5.webp",
      "imagens/asx/6.webp",
      "imagens/asx/7.webp",
      "imagens/asx/8.webp"
    ]
  },
  {
    "id": "mitsubishi-pajero",
    "brand": "Mitsubishi",
    "bk": "mitsubishi",
    "model": "PAJERO TR4 FLEX HP",
    "year": "2013/2013",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/pajero.webp",
    "folder": "pajero",
    "price": "R$62.000,00",
    "cambio": "Automatico",
    "desc": "",
    "photos": [
      "imagens/pajero/1.webp",
      "imagens/pajero/2.webp",
      "imagens/pajero/3.webp",
      "imagens/pajero/4.webp",
      "imagens/pajero/5.webp",
      "imagens/pajero/6.webp",
      "imagens/pajero/7.webp",
      "imagens/pajero/8.webp"
    ]
  },
  {
    "id": "peugeot-504",
    "brand": "Peugeot",
    "bk": "outros",
    "model": "504 GRD",
    "year": "1995/1996",
    "color": "Vermelha",
    "hex": "#c0392b",
    "fuel": "diesel",
    "extra": null,
    "classic": true,
    "img": "imagens/peugeot504.webp",
    "folder": "peugeot504",
    "price": "R$50.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/peugeot504/1.webp",
      "imagens/peugeot504/2.webp",
      "imagens/peugeot504/3.webp",
      "imagens/peugeot504/4.webp",
      "imagens/peugeot504/5.webp",
      "imagens/peugeot504/6.webp",
      "imagens/peugeot504/7.webp",
      "imagens/peugeot504/8.webp"
    ]
  },
  {
    "id": "renault-duster",
    "brand": "Renault",
    "bk": "outros",
    "model": "DUSTER 16E 4X2",
    "year": "2012/2013",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/duster.webp",
    "folder": "duster",
    "price": "R$49.500,00",
    "cambio": "Automatico",
    "desc": "",
    "photos": [
      "imagens/duster/1.webp",
      "imagens/duster/2.webp",
      "imagens/duster/3.webp",
      "imagens/duster/4.webp",
      "imagens/duster/5.webp",
      "imagens/duster/6.webp",
      "imagens/duster/7.webp",
      "imagens/duster/8.webp"
    ]
  },
  {
    "id": "vw-brasilia",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "BRASILIA",
    "year": "1978/1978",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "gasolina",
    "extra": null,
    "classic": true,
    "img": "imagens/brasilia.webp",
    "folder": "brasilia",
    "price": "R$35.000,00",
    "cambio": "Manual",
    "desc": "Dispensa comentarios, esse modelo esta em perfeito estado de conservacao",
    "photos": [
      "imagens/brasilia/1.webp",
      "imagens/brasilia/2.webp",
      "imagens/brasilia/3.webp",
      "imagens/brasilia/4.webp",
      "imagens/brasilia/5.webp",
      "imagens/brasilia/6.webp",
      "imagens/brasilia/7.webp",
      "imagens/brasilia/8.webp"
    ]
  },
  {
    "id": "vw-fox",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "FOX ROCK RIO MB",
    "year": "2015/2016",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/fox.webp",
    "folder": "fox",
    "price": "R$54.000,00",
    "cambio": "Manual",
    "desc": "Perfeito estado, podemos dizer novo",
    "photos": [
      "imagens/fox/1.webp",
      "imagens/fox/2.webp",
      "imagens/fox/3.webp",
      "imagens/fox/4.webp",
      "imagens/fox/5.webp",
      "imagens/fox/6.webp",
      "imagens/fox/7.webp",
      "imagens/fox/8.webp"
    ]
  },
  {
    "id": "vw-fusca",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "FUSCA 1500",
    "year": "1972/1972",
    "color": "Verde",
    "hex": "#27ae60",
    "fuel": "gasolina",
    "extra": null,
    "classic": true,
    "img": "imagens/fusca.webp",
    "folder": "fusca",
    "price": "R$68.000,00",
    "cambio": "Manual",
    "desc": "Nostalgia, pintura impecavel, muito bem conservado",
    "photos": [
      "imagens/fusca/1.webp",
      "imagens/fusca/2.webp",
      "imagens/fusca/3.webp",
      "imagens/fusca/4.webp",
      "imagens/fusca/5.webp",
      "imagens/fusca/6.webp",
      "imagens/fusca/7.webp",
      "imagens/fusca/8.webp"
    ]
  },
  {
    "id": "vw-gol-18gli",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "GOL 1.8 GLI",
    "year": "1995/1995",
    "color": "Azul",
    "hex": "#2980b9",
    "fuel": "gasolina",
    "extra": null,
    "classic": true,
    "img": "imagens/gol18gli.webp",
    "folder": "gol18gli",
    "price": "R$28.500,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/gol18gli/1.webp",
      "imagens/gol18gli/2.webp",
      "imagens/gol18gli/3.webp",
      "imagens/gol18gli/4.webp",
      "imagens/gol18gli/5.webp",
      "imagens/gol18gli/6.webp",
      "imagens/gol18gli/7.webp",
      "imagens/gol18gli/8.webp"
    ]
  },
  {
    "id": "vw-gol-novo",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "GOL 1.0 NOVO",
    "year": "2013/2013",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/gol.webp",
    "folder": "gol",
    "price": "R$33.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/gol/1.webp",
      "imagens/gol/2.webp",
      "imagens/gol/3.webp",
      "imagens/gol/4.webp",
      "imagens/gol/5.webp",
      "imagens/gol/6.webp",
      "imagens/gol/7.webp",
      "imagens/gol/8.webp"
    ]
  },
  {
    "id": "vw-gol-gls",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "GOL GLS 2.0 MI",
    "year": "1998/1998",
    "color": "Cinza",
    "hex": "#9ba3b0",
    "fuel": "gasolina",
    "extra": null,
    "classic": true,
    "img": "imagens/golgls2.0.webp",
    "folder": "golgls2.0",
    "price": "R$40.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/golgls2.0/1.webp",
      "imagens/golgls2.0/2.webp",
      "imagens/golgls2.0/3.webp",
      "imagens/golgls2.0/4.webp",
      "imagens/golgls2.0/5.webp",
      "imagens/golgls2.0/6.webp",
      "imagens/golgls2.0/7.webp",
      "imagens/golgls2.0/8.webp"
    ]
  },
  {
    "id": "vw-gol-tl",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "GOL TL",
    "year": "2018/2018",
    "color": "Cinza",
    "hex": "#9ba3b0",
    "fuel": "flex",
    "extra": "Vendido",
    "classic": false,
    "img": "imagens/goltl.webp",
    "folder": "goltl",
    "price": "Vendido",
    "cambio": "",
    "desc": "Carro perfeito, rodas de liga leve aro 18",
    "photos": [
      "imagens/goltl/1.webp",
      "imagens/goltl/2.webp",
      "imagens/goltl/3.webp",
      "imagens/goltl/4.webp",
      "imagens/goltl/5.webp",
      "imagens/goltl/6.webp",
      "imagens/goltl/7.webp",
      "imagens/goltl/8.webp"
    ]
  },
  {
    "id": "vw-jetta",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "JETTA HL AE",
    "year": "2016/2016",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "gasolina",
    "extra": null,
    "classic": false,
    "img": "imagens/jetta.webp",
    "folder": "jetta",
    "price": "R$90.000,00",
    "cambio": "Automatico",
    "desc": "Todos os comandos em perfeito estado, estofamento em couro",
    "photos": [
      "imagens/jetta/1.webp",
      "imagens/jetta/2.webp",
      "imagens/jetta/3.webp",
      "imagens/jetta/4.webp",
      "imagens/jetta/5.webp",
      "imagens/jetta/6.webp",
      "imagens/jetta/7.webp",
      "imagens/jetta/8.webp"
    ]
  },
  {
    "id": "vw-kombi",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "KOMBI",
    "year": "2011/2012",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/kombi.webp",
    "folder": "kombi",
    "price": "R$75.000,00",
    "cambio": "KombiHome",
    "desc": "Pronta para pegar a estrada: cama, armarios, ventiladores, mesa, pia, TV",
    "photos": [
      "imagens/kombi/1.webp",
      "imagens/kombi/2.webp",
      "imagens/kombi/3.webp",
      "imagens/kombi/4.webp",
      "imagens/kombi/5.webp",
      "imagens/kombi/6.webp",
      "imagens/kombi/7.webp",
      "imagens/kombi/8.webp"
    ]
  },
  {
    "id": "vw-saveiro-cs",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "SAVEIRO 1.6 CS",
    "year": "2012/2013",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/saveiro.webp",
    "folder": "saveiro",
    "price": "R$43.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/saveiro/1.webp",
      "imagens/saveiro/2.webp",
      "imagens/saveiro/3.webp",
      "imagens/saveiro/4.webp",
      "imagens/saveiro/5.webp",
      "imagens/saveiro/6.webp",
      "imagens/saveiro/7.webp",
      "imagens/saveiro/8.webp"
    ]
  },
  {
    "id": "vw-saveiro-prata",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "SAVEIRO 1.6 CS",
    "year": "2011/2011",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/saveiroprata.webp",
    "folder": "saveiroprata",
    "price": "R$38.500,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/saveiroprata/1.webp",
      "imagens/saveiroprata/2.webp",
      "imagens/saveiroprata/3.webp",
      "imagens/saveiroprata/4.webp",
      "imagens/saveiroprata/5.webp",
      "imagens/saveiroprata/6.webp",
      "imagens/saveiroprata/7.webp",
      "imagens/saveiroprata/8.webp"
    ]
  },
  {
    "id": "vw-saveiro-surf",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "SAVEIRO 1.6 SURF",
    "year": "2009/2010",
    "color": "Vermelha",
    "hex": "#c0392b",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/saveirosurt.webp",
    "folder": "saveirosurf",
    "price": "R$57.000,00",
    "cambio": "Manual",
    "desc": "Rebaixada, motor preparado, para quem gosta de velocidade",
    "photos": [
      "imagens/saveirosurf/1.webp",
      "imagens/saveirosurf/2.webp",
      "imagens/saveirosurf/3.webp",
      "imagens/saveirosurf/4.webp",
      "imagens/saveirosurf/5.webp",
      "imagens/saveirosurf/6.webp",
      "imagens/saveirosurf/7.webp",
      "imagens/saveirosurf/8.webp"
    ]
  },
  {
    "id": "vw-saveiro-99",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "SAVEIRO 1.6 MI",
    "year": "1999/1999",
    "color": "Vermelha",
    "hex": "#c0392b",
    "fuel": "gasolina",
    "extra": null,
    "classic": true,
    "img": "imagens/saveiro99.webp",
    "folder": "saveiro99",
    "price": "R$33.000,00",
    "cambio": "Manual",
    "desc": "Muito bem conservada, raridade",
    "photos": [
      "imagens/saveiro99/1.webp",
      "imagens/saveiro99/2.webp",
      "imagens/saveiro99/3.webp",
      "imagens/saveiro99/4.webp",
      "imagens/saveiro99/5.webp",
      "imagens/saveiro99/6.webp",
      "imagens/saveiro99/7.webp",
      "imagens/saveiro99/8.webp"
    ]
  },
  {
    "id": "vw-up",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "UP 1.0 NOVO",
    "year": "2017/2018",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/up.webp",
    "folder": "up",
    "price": "R$33.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/up/1.webp",
      "imagens/up/2.webp",
      "imagens/up/3.webp",
      "imagens/up/4.webp",
      "imagens/up/5.webp",
      "imagens/up/6.webp",
      "imagens/up/7.webp",
      "imagens/up/8.webp"
    ]
  },
  {
    "id": "vw-voyage",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "VOYAGE MPI",
    "year": "2022/2023",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/voyagempi.webp",
    "folder": "voyage",
    "price": "R$55.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "imagens/voyage/1.webp",
      "imagens/voyage/2.webp",
      "imagens/voyage/3.webp",
      "imagens/voyage/4.webp",
      "imagens/voyage/5.webp",
      "imagens/voyage/6.webp",
      "imagens/voyage/7.webp",
      "imagens/voyage/8.webp"
    ]
  },
  {
    "id": "nissan-versa",
    "brand": "Nissan",
    "bk": "outros",
    "model": "VERSA 1.6 SV",
    "year": "2012/2013",
    "color": "Cinza",
    "hex": "#9ba3b0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "imagens/versa.webp",
    "folder": "versa",
    "price": "R$55.000,00",
    "cambio": "Automatico",
    "desc": "",
    "photos": [
      "imagens/versa/1.webp",
      "imagens/versa/2.webp",
      "imagens/versa/3.webp",
      "imagens/versa/4.webp",
      "imagens/versa/5.webp",
      "imagens/versa/6.webp",
      "imagens/versa/7.webp",
      "imagens/versa/8.webp"
    ]
  }
]
;
