const vehicles = 
[
  {
    "id": "bmw-x1",
    "brand": "BMW",
    "bk": "outros",
    "model": "X1 SDRIVE 1.8I",
    "year": "2011/2011",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "gasolina",
    "extra": "Vendido",
    "classic": false,
    "img": "bmwx1/1.webp",
    "folder": "bmwx1",
    "price": "Vendido",
    "cambio": "",
    "desc": "",
    "photos": [
      "bmwx1/1.webp",
      "bmwx1/2.webp",
      "bmwx1/3.webp",
      "bmwx1/4.webp",
      "bmwx1/5.webp",
      "bmwx1/6.webp",
      "bmwx1/7.webp",
      "bmwx1/8.webp"
    ]
  },
  {
    "id": "willys-overland",
    "brand": "Willys",
    "bk": "outros",
    "model": "OVERLAND",
    "year": "1951/1951",
    "color": "Verde",
    "hex": "#4a7c59",
    "fuel": "gasolina",
    "extra": null,
    "classic": true,
    "img": "willys/1.webp",
    "folder": "willys",
    "price": "R$50.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "willys/1.webp",
      "willys/2.webp",
      "willys/3.webp",
      "willys/4.webp",
      "willys/5.webp",
      "willys/6.webp",
      "willys/7.webp",
      "willys/8.webp"
    ]
  },
  {
    "id": "chevrolet-agile",
    "brand": "Chevrolet",
    "bk": "chevrolet",
    "model": "AGILE LTZ",
    "year": "2012/2013",
    "color": "Cinza",
    "hex": "#9ba3b0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "agile/1.webp",
    "folder": "agile",
    "price": "Vendido",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "agile/1.webp",
      "agile/2.webp",
      "agile/3.webp",
      "agile/4.webp",
      "agile/5.webp",
      "agile/6.webp",
      "agile/7.webp",
      "agile/8.webp"
    ]
  },
  {
    "id": "chevrolet-astra",
    "brand": "Chevrolet",
    "bk": "chevrolet",
    "model": "ASTRA ADVANTAGE 2.0",
    "year": "2011/2011",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "astra/1.webp",
    "folder": "astra",
    "price": "R$40.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "astra/1.webp",
      "astra/2.webp",
      "astra/3.webp",
      "astra/4.webp",
      "astra/5.webp",
      "astra/6.webp",
      "astra/7.webp",
      "astra/8.webp"
    ]
  },
  {
    "id": "chevrolet-cruze",
    "brand": "Chevrolet",
    "bk": "chevrolet",
    "model": "CRUZE LT NB",
    "year": "2012/2012",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "cruze/1.webp",
    "folder": "cruze",
    "price": "R$55.000,00",
    "cambio": "Automatico",
    "desc": "",
    "photos": [
      "cruze/1.webp",
      "cruze/2.webp",
      "cruze/3.webp",
      "cruze/4.webp",
      "cruze/5.webp",
      "cruze/6.webp",
      "cruze/7.webp",
      "cruze/8.webp"
    ]
  },
  {
    "id": "chevrolet-onix",
    "brand": "Chevrolet",
    "bk": "chevrolet",
    "model": "ONIX 1.4 LT",
    "year": "2016/2017",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": "Vendido",
    "classic": false,
    "img": "onix/1.webp",
    "folder": "onix",
    "price": "Vendido",
    "cambio": "",
    "desc": "",
    "photos": [
      "onix/1.webp",
      "onix/2.webp",
      "onix/3.webp",
      "onix/4.webp",
      "onix/5.webp",
      "onix/6.webp",
      "onix/7.webp",
      "onix/8.webp"
    ]
  },
  {
    "id": "gm-celta",
    "brand": "GM",
    "bk": "chevrolet",
    "model": "CELTA 2P SPIRIT",
    "year": "2007/2008",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "celta/1.webp",
    "folder": "celta",
    "price": "R$25.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "celta/1.webp",
      "celta/2.webp",
      "celta/3.webp",
      "celta/4.webp",
      "celta/5.webp",
      "celta/6.webp",
      "celta/7.webp",
      "celta/8.webp"
    ]
  },
  {
    "id": "gm-meriva-preto",
    "brand": "GM",
    "bk": "chevrolet",
    "model": "MERIVA PREMIUM",
    "year": "2008/2008",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "merivapreto/1.webp",
    "folder": "merivapreto",
    "price": "R$26.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "merivapreto/1.webp",
      "merivapreto/2.webp",
      "merivapreto/3.webp",
      "merivapreto/4.webp",
      "merivapreto/5.webp",
      "merivapreto/6.webp",
      "merivapreto/7.webp",
      "merivapreto/8.webp"
    ]
  },
  {
    "id": "gm-meriva-verde",
    "brand": "GM",
    "bk": "chevrolet",
    "model": "MERIVA PREMIUM",
    "year": "2010/2011",
    "color": "Verde",
    "hex": "#27ae60",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "meriva/1.webp",
    "folder": "meriva",
    "price": "R$35.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "meriva/1.webp",
      "meriva/2.webp",
      "meriva/3.webp",
      "meriva/4.webp",
      "meriva/5.webp",
      "meriva/6.webp",
      "meriva/7.webp",
      "meriva/8.webp"
    ]
  },
  {
    "id": "gm-s10",
    "brand": "GM",
    "bk": "chevrolet",
    "model": "S10 ADVANTAGE S",
    "year": "2009/2009",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "flex",
    "extra": "Vendido",
    "classic": false,
    "img": "s10/1.webp",
    "folder": "s10",
    "price": "Vendido",
    "cambio": "",
    "desc": "",
    "photos": [
      "s10/1.webp",
      "s10/2.webp",
      "s10/3.webp",
      "s10/4.webp",
      "s10/5.webp",
      "s10/6.webp",
      "s10/7.webp",
      "s10/8.webp"
    ]
  },
  {
    "id": "fiat-punto-prata",
    "brand": "Fiat",
    "bk": "fiat",
    "model": "PUNTO ATTRACTIVE",
    "year": "2016/2016",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "puntoprata/1.webp",
    "folder": "puntoprata",
    "price": "R$46.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "puntoprata/1.webp",
      "puntoprata/2.webp",
      "puntoprata/3.webp",
      "puntoprata/4.webp",
      "puntoprata/5.webp",
      "puntoprata/6.webp",
      "puntoprata/7.webp",
      "puntoprata/8.webp"
    ]
  },
  {
    "id": "fiat-punto-essence",
    "brand": "Fiat",
    "bk": "fiat",
    "model": "PUNTO ATTRACTIVE",
    "year": "2011/2012",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "puntopreto/1.webp",
    "folder": "puntopreto",
    "price": "R$35.000,00",
    "cambio": "Automatico",
    "desc": "",
    "photos": [
      "puntopreto/1.webp",
      "puntopreto/2.webp",
      "puntopreto/3.webp",
      "puntopreto/4.webp",
      "puntopreto/5.webp",
      "puntopreto/6.webp",
      "puntopreto/7.webp",
      "puntopreto/8.webp"
    ]
  },
  {
    "id": "fiat-uno-mille",
    "brand": "Fiat",
    "bk": "fiat",
    "model": "UNO MILLE ECONOMY",
    "year": "2013/2013",
    "color": "Azul Escuro",
    "hex": "#1a3a5c",
    "fuel": "flex",
    "extra": "Vendido",
    "classic": false,
    "img": "unomille/1.webp",
    "folder": "unomille",
    "price": "Vendido",
    "cambio": "",
    "desc": "",
    "photos": [
      "unomille/1.webp",
      "unomille/2.webp",
      "unomille/3.webp",
      "unomille/4.webp",
      "unomille/5.webp",
      "unomille/6.webp",
      "unomille/7.webp",
      "unomille/8.webp"
    ]
  },
  {
    "id": "fiat-uno-vivace",
    "brand": "Fiat",
    "bk": "fiat",
    "model": "UNO VIVACE 1.0",
    "year": "2010/2011",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "unovivace/1.webp",
    "folder": "unovivace",
    "price": "R$33.500,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "unovivace/1.webp",
      "unovivace/2.webp",
      "unovivace/3.webp",
      "unovivace/4.webp",
      "unovivace/5.webp",
      "unovivace/6.webp",
      "unovivace/7.webp",
      "unovivace/8.webp"
    ]
  },
  {
    "id": "ford-fiesta",
    "brand": "Ford",
    "bk": "ford",
    "model": "FIESTA",
    "year": "2009/2010",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "fiesta/1.webp",
    "folder": "fiesta",
    "price": "R$32.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "fiesta/1.webp",
      "fiesta/2.webp",
      "fiesta/3.webp",
      "fiesta/4.webp",
      "fiesta/5.webp",
      "fiesta/6.webp",
      "fiesta/7.webp",
      "fiesta/8.webp"
    ]
  },
  {
    "id": "ford-focus",
    "brand": "Ford",
    "bk": "ford",
    "model": "FOCUS TITANIUM 2.0",
    "year": "2014/2015",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "focus/1.webp",
    "folder": "focus",
    "price": "R$ 45.000",
    "cambio": "",
    "desc": "",
    "photos": [
      "focus/1.webp",
      "focus/2.webp",
      "focus/3.webp",
      "focus/4.webp",
      "focus/5.webp",
      "focus/6.webp",
      "focus/7.webp",
      "focus/8.webp"
    ]
  },
  {
    "id": "ford-ka",
    "brand": "Ford",
    "bk": "ford",
    "model": "KA 1.0 SEL",
    "year": "2015/2015",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "ka/1.webp",
    "folder": "ka",
    "price": "R$42.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "ka/1.webp",
      "ka/2.webp",
      "ka/3.webp",
      "ka/4.webp",
      "ka/5.webp",
      "ka/6.webp",
      "ka/7.webp",
      "ka/8.webp"
    ]
  },
  {
    "id": "ford-maverick",
    "brand": "Ford",
    "bk": "ford",
    "model": "MAVERICK",
    "year": "1978/1979",
    "color": "Cinza",
    "hex": "#9ba3b0",
    "fuel": "gasolina",
    "extra": null,
    "classic": true,
    "img": "maverick/1.webp",
    "folder": "maverick",
    "price": "R$260.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "maverick/1.webp",
      "maverick/2.webp",
      "maverick/3.webp",
      "maverick/4.webp",
      "maverick/5.webp",
      "maverick/6.webp",
      "maverick/7.webp",
      "maverick/8.webp"
    ]
  },
  {
    "id": "hyundai-hb20",
    "brand": "Hyundai",
    "bk": "outros",
    "model": "HB20 1.6",
    "year": "2019/2019",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "hb20/1.webp",
    "folder": "hb20",
    "price": "",
    "cambio": "",
    "desc": "",
    "photos": [
      "hb20/1.webp",
      "hb20/2.webp",
      "hb20/3.webp",
      "hb20/4.webp",
      "hb20/5.webp",
      "hb20/6.webp",
      "hb20/7.webp",
      "hb20/8.webp"
    ]
  },
  {
    "id": "hyundai-hr",
    "brand": "Hyundai",
    "bk": "outros",
    "model": "HR HDB",
    "year": "2012/2013",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "diesel",
    "extra": null,
    "classic": false,
    "img": "hyundaihr/1.webp",
    "folder": "hyundaihr",
    "price": "R$89.900,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "hyundaihr/1.webp",
      "hyundaihr/2.webp",
      "hyundaihr/3.webp",
      "hyundaihr/4.webp",
      "hyundaihr/5.webp",
      "hyundaihr/6.webp",
      "hyundaihr/7.webp",
      "hyundaihr/8.webp"
    ]
  },
  {
    "id": "hyundai-tucson",
    "brand": "Hyundai",
    "bk": "hyundai",
    "model": "TUCSON GLSB",
    "year": "2012/2013",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "gasolina",
    "extra": null,
    "classic": false,
    "img": "Tucson/1.webp",
    "folder": "Tucson",
    "price": "R$50.500,00",
    "cambio": "Automatico",
    "desc": "",
    "photos": [
      "https://d2xsxph8kpxj0f.cloudfront.net/310519663389657681/3zSJVq9qjkbxu9s8RVd9jK/1_fca99f0a.webp",
      "https://d2xsxph8kpxj0f.cloudfront.net/310519663389657681/3zSJVq9qjkbxu9s8RVd9jK/3_c71e76a2.webp",
      "https://d2xsxph8kpxj0f.cloudfront.net/310519663389657681/3zSJVq9qjkbxu9s8RVd9jK/6_6ab7dbdb.webp"
    ]
  },
  {
    "id": "kia-uk2500",
    "brand": "Kia Motors",
    "bk": "outros",
    "model": "UK2500 HD SC",
    "year": "2013/2014",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "diesel",
    "extra": null,
    "classic": false,
    "img": "kia/1.webp",
    "folder": "kia",
    "price": "R$150.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "kia/1.webp",
      "kia/2.webp",
      "kia/3.webp",
      "kia/4.webp",
      "kia/5.webp",
      "kia/6.webp",
      "kia/7.webp",
      "kia/8.webp"
    ]
  },
  {
    "id": "mitsubishi-asx",
    "brand": "Mitsubishi",
    "bk": "mitsubishi",
    "model": "ASX 2.0 4WD",
    "year": "2013/2013",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "asx/1.webp",
    "folder": "asx",
    "price": "R$74.000,00",
    "cambio": "Automatico",
    "desc": "",
    "photos": [
      "asx/1.webp",
      "asx/2.webp",
      "asx/3.webp",
      "asx/4.webp",
      "asx/5.webp",
      "asx/6.webp",
      "asx/7.webp",
      "asx/8.webp"
    ]
  },
  {
    "id": "mitsubishi-pajero",
    "brand": "Mitsubishi",
    "bk": "mitsubishi",
    "model": "PAJERO TR4 FLEX HP",
    "year": "2013/2013",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "pajero/1.webp",
    "folder": "pajero",
    "price": "R$62.000,00",
    "cambio": "Automatico",
    "desc": "",
    "photos": [
      "pajero/1.webp",
      "pajero/2.webp",
      "pajero/3.webp",
      "pajero/4.webp",
      "pajero/5.webp",
      "pajero/6.webp",
      "pajero/7.webp",
      "pajero/8.webp"
    ]
  },
  {
    "id": "peugeot-504",
    "brand": "Peugeot",
    "bk": "outros",
    "model": "504 GRD",
    "year": "1995/1996",
    "color": "Vermelha",
    "hex": "#c0392b",
    "fuel": "diesel",
    "extra": null,
    "classic": true,
    "img": "peugeot504/1.webp",
    "folder": "peugeot504",
    "price": "R$50.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "peugeot504/1.webp",
      "peugeot504/2.webp",
      "peugeot504/3.webp",
      "peugeot504/4.webp",
      "peugeot504/5.webp",
      "peugeot504/6.webp",
      "peugeot504/7.webp",
      "peugeot504/8.webp"
    ]
  },
  {
    "id": "renault-duster",
    "brand": "Renault",
    "bk": "outros",
    "model": "DUSTER 16E 4X2",
    "year": "2012/2013",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "duster/1.webp",
    "folder": "duster",
    "price": "R$49.500,00",
    "cambio": "Automatico",
    "desc": "",
    "photos": [
      "duster/1.webp",
      "duster/2.webp",
      "duster/3.webp",
      "duster/4.webp",
      "duster/5.webp",
      "duster/6.webp",
      "duster/7.webp",
      "duster/8.webp"
    ]
  },
  {
    "id": "vw-brasilia",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "BRASILIA",
    "year": "1978/1978",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "gasolina",
    "extra": null,
    "classic": true,
    "img": "brasilia/1.webp",
    "folder": "brasilia",
    "price": "R$35.000,00",
    "cambio": "Manual",
    "desc": "Dispensa comentarios, esse modelo esta em perfeito estado de conservacao",
    "photos": [
      "brasilia/1.webp",
      "brasilia/2.webp",
      "brasilia/3.webp",
      "brasilia/4.webp",
      "brasilia/5.webp",
      "brasilia/6.webp",
      "brasilia/7.webp",
      "brasilia/8.webp"
    ]
  },
  {
    "id": "vw-fox",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "FOX ROCK RIO MB",
    "year": "2015/2016",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "fox/1.webp",
    "folder": "fox",
    "price": "R$54.000,00",
    "cambio": "Manual",
    "desc": "Perfeito estado, podemos dizer novo",
    "photos": [
      "fox/1.webp",
      "fox/2.webp",
      "fox/3.webp",
      "fox/4.webp",
      "fox/5.webp",
      "fox/6.webp",
      "fox/7.webp",
      "fox/8.webp"
    ]
  },
  {
    "id": "vw-fusca",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "FUSCA 1500",
    "year": "1972/1972",
    "color": "Verde",
    "hex": "#27ae60",
    "fuel": "gasolina",
    "extra": null,
    "classic": true,
    "img": "fusca/1.webp",
    "folder": "fusca",
    "price": "R$68.000,00",
    "cambio": "Manual",
    "desc": "Nostalgia, pintura impecavel, muito bem conservado",
    "photos": [
      "fusca/1.webp",
      "fusca/2.webp",
      "fusca/3.webp",
      "fusca/4.webp",
      "fusca/5.webp",
      "fusca/6.webp",
      "fusca/7.webp",
      "fusca/8.webp"
    ]
  },
  {
    "id": "vw-gol-18gli",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "GOL 1.8 GLI",
    "year": "1995/1995",
    "color": "Azul",
    "hex": "#2980b9",
    "fuel": "gasolina",
    "extra": null,
    "classic": true,
    "img": "gol18gli/1.webp",
    "folder": "gol18gli",
    "price": "R$28.500,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "gol18gli/1.webp",
      "gol18gli/2.webp",
      "gol18gli/3.webp",
      "gol18gli/4.webp",
      "gol18gli/5.webp",
      "gol18gli/6.webp",
      "gol18gli/7.webp",
      "gol18gli/8.webp"
    ]
  },
  {
    "id": "vw-gol-novo",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "GOL 1.0 NOVO",
    "year": "2013/2013",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "gol/1.webp",
    "folder": "gol",
    "price": "R$33.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "gol/1.webp",
      "gol/2.webp",
      "gol/3.webp",
      "gol/4.webp",
      "gol/5.webp",
      "gol/6.webp",
      "gol/7.webp",
      "gol/8.webp"
    ]
  },
  {
    "id": "vw-gol-gls",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "GOL GLS 2.0 MI",
    "year": "1998/1998",
    "color": "Cinza",
    "hex": "#9ba3b0",
    "fuel": "gasolina",
    "extra": null,
    "classic": true,
    "img": "golgls2.0/1.webp",
    "folder": "golgls2.0",
    "price": "R$40.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "golgls2.0/1.webp",
      "golgls2.0/2.webp",
      "golgls2.0/3.webp",
      "golgls2.0/4.webp",
      "golgls2.0/5.webp",
      "golgls2.0/6.webp",
      "golgls2.0/7.webp",
      "golgls2.0/8.webp"
    ]
  },
  {
    "id": "vw-gol-tl",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "GOL TL",
    "year": "2018/2018",
    "color": "Cinza",
    "hex": "#9ba3b0",
    "fuel": "flex",
    "extra": "Vendido",
    "classic": false,
    "img": "goltl/1.webp",
    "folder": "goltl",
    "price": "Vendido",
    "cambio": "",
    "desc": "Carro perfeito, rodas de liga leve aro 18",
    "photos": [
      "goltl/1.webp",
      "goltl/2.webp",
      "goltl/3.webp",
      "goltl/4.webp",
      "goltl/5.webp",
      "goltl/6.webp",
      "goltl/7.webp",
      "goltl/8.webp"
    ]
  },
  {
    "id": "vw-jetta",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "JETTA HL AE",
    "year": "2016/2016",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "gasolina",
    "extra": null,
    "classic": false,
    "img": "jetta/1.webp",
    "folder": "jetta",
    "price": "R$90.000,00",
    "cambio": "Automatico",
    "desc": "Todos os comandos em perfeito estado, estofamento em couro",
    "photos": [
      "jetta/1.webp",
      "jetta/2.webp",
      "jetta/3.webp",
      "jetta/4.webp",
      "jetta/5.webp",
      "jetta/6.webp",
      "jetta/7.webp",
      "jetta/8.webp"
    ]
  },
  {
    "id": "vw-kombi",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "KOMBI",
    "year": "2011/2012",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "kombi/1.webp",
    "folder": "kombi",
    "price": "R$75.000,00",
    "cambio": "KombiHome",
    "desc": "Pronta para pegar a estrada: cama, armarios, ventiladores, mesa, pia, TV",
    "photos": [
      "kombi/1.webp",
      "kombi/2.webp",
      "kombi/3.webp",
      "kombi/4.webp",
      "kombi/5.webp",
      "kombi/6.webp",
      "kombi/7.webp",
      "kombi/8.webp"
    ]
  },
  {
    "id": "vw-saveiro-cs",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "SAVEIRO 1.6 CS",
    "year": "2012/2013",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "saveiro/1.webp",
    "folder": "saveiro",
    "price": "R$43.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "saveiro/1.webp",
      "saveiro/2.webp",
      "saveiro/3.webp",
      "saveiro/4.webp",
      "saveiro/5.webp",
      "saveiro/6.webp",
      "saveiro/7.webp",
      "saveiro/8.webp"
    ]
  },
  {
    "id": "vw-saveiro-prata",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "SAVEIRO 1.6 CS",
    "year": "2011/2011",
    "color": "Prata",
    "hex": "#c0c8d0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "saveiroprata/1.webp",
    "folder": "saveiroprata",
    "price": "R$38.500,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "saveiroprata/1.webp",
      "saveiroprata/2.webp",
      "saveiroprata/3.webp",
      "saveiroprata/4.webp",
      "saveiroprata/5.webp",
      "saveiroprata/6.webp",
      "saveiroprata/7.webp",
      "saveiroprata/8.webp"
    ]
  },
  {
    "id": "vw-saveiro-surf",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "SAVEIRO 1.6 SURF",
    "year": "2009/2010",
    "color": "Vermelha",
    "hex": "#c0392b",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "saveirosurf/1.webp",
    "folder": "saveirosurf",
    "price": "R$57.000,00",
    "cambio": "Manual",
    "desc": "Rebaixada, motor preparado, para quem gosta de velocidade",
    "photos": [
      "saveirosurf/1.webp",
      "saveirosurf/2.webp",
      "saveirosurf/3.webp",
      "saveirosurf/4.webp",
      "saveirosurf/5.webp",
      "saveirosurf/6.webp",
      "saveirosurf/7.webp",
      "saveirosurf/8.webp"
    ]
  },
  {
    "id": "vw-saveiro-99",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "SAVEIRO 1.6 MI",
    "year": "1999/1999",
    "color": "Vermelha",
    "hex": "#c0392b",
    "fuel": "gasolina",
    "extra": null,
    "classic": true,
    "img": "saveiro99/1.webp",
    "folder": "saveiro99",
    "price": "R$33.000,00",
    "cambio": "Manual",
    "desc": "Muito bem conservada, raridade",
    "photos": [
      "saveiro99/1.webp",
      "saveiro99/2.webp",
      "saveiro99/3.webp",
      "saveiro99/4.webp",
      "saveiro99/5.webp",
      "saveiro99/6.webp",
      "saveiro99/7.webp",
      "saveiro99/8.webp"
    ]
  },
  {
    "id": "vw-up",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "UP 1.0 NOVO",
    "year": "2017/2018",
    "color": "Preta",
    "hex": "#1a1a1a",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "up/1.webp",
    "folder": "up",
    "price": "R$33.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "up/1.webp",
      "up/2.webp",
      "up/3.webp",
      "up/4.webp",
      "up/5.webp",
      "up/6.webp",
      "up/7.webp",
      "up/8.webp"
    ]
  },
  {
    "id": "vw-voyage",
    "brand": "Volkswagen",
    "bk": "volkswagen",
    "model": "VOYAGE MPI",
    "year": "2022/2023",
    "color": "Branca",
    "hex": "#f0f2f5",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "voyage/1.webp",
    "folder": "voyage",
    "price": "R$55.000,00",
    "cambio": "Manual",
    "desc": "",
    "photos": [
      "voyage/1.webp",
      "voyage/2.webp",
      "voyage/3.webp",
      "voyage/4.webp",
      "voyage/5.webp",
      "voyage/6.webp",
      "voyage/7.webp",
      "voyage/8.webp"
    ]
  },
  {
    "id": "nissan-versa",
    "brand": "Nissan",
    "bk": "outros",
    "model": "VERSA 1.6 SV",
    "year": "2012/2013",
    "color": "Cinza",
    "hex": "#9ba3b0",
    "fuel": "flex",
    "extra": null,
    "classic": false,
    "img": "versa/1.webp",
    "folder": "versa",
    "price": "R$55.000,00",
    "cambio": "Automatico",
    "desc": "",
    "photos": [
      "versa/1.webp",
      "versa/2.webp",
      "versa/3.webp",
      "versa/4.webp",
      "versa/5.webp",
      "versa/6.webp",
      "versa/7.webp",
      "versa/8.webp"
    ]
  }
]